spring:
  application:
    name: hystrix-consumer
  rabbitmq:
    host: 10.48.114.26
    port: 5672
    username: springcloud
    password: rss123
server:
  port: 9990
logging:
  level:
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9998/eureka/,http://127.0.0.1:9997/eureka/
  instance:
    metadata-map.cluster: MAIN