server:
  port: 9999

management:
  security:
    enabled: false
    
spring:
  cloud:
    config:
      server:
        git:
          uri: git@10.48.114.26:cdn/config_server.git
          searchPaths: dsi_java
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9998/eureka/,http://127.0.0.1:9997/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    