spring:
  application:
    name: eureka-server
server:
  port: 9997
logging:
  level:
    root: INFO
eureka:
#  server:
#    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9998/eureka/