spring:
  application:
    name: eureka-server
server:
  port: 9998
logging:
  level:
    root: INFO
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9997/eureka/