spring:
  application:
    name: eureka-server
server:
  port: 9997
logging:
  level:
    root: INFO
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9998/eureka/