spring:
  application:
    name: zuul-server
server:
  port: 9986
management:
  security:
    enabled: false
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:9998/eureka/,http://127.0.0.1:9997/eureka/
      
zuul:
  route:
    api-a:
      path: /api-a/**
      serviceId: CONFIG-SERVER
    api-b:
      path: /api-b/**
      serviceId: FEGIN-CONSUMER
