spring:
  application:
    name: ribbon-consumer
server:
  port: 9991
logging:
  level:
    root: info
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:9998/eureka/,http://127.0.0.1:9997/eureka/